apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: scaletestapp-monitor
  namespace: monitoring
  labels:
    release: prometheus

spec:
  selector:
    matchLabels:
      app: scaletestapp
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: http
      path: /metrics
      interval: 10s
